source 'https://rubygems.org'

gem 'rails', '4.2.0.rc1'
gem 'sqlite3'
gem 'sass-rails', '>= 3.2'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'haml-rails'
gem 'netguru_bootstrapper'
gem 'bootstrap-sass', '~> 3.3.1'
gem 'faker'
gem 'speech2text'
gem 'simple_form'
gem 'bcrypt-ruby', '3.1.2'
gem 'pry-byebug'
